steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build --build-arg PM2_PUBLIC_KEY=$$PM2_PUBLIC_KEY --build-arg PM2_SECRET_KEY=$$PM2_SECRET_KEY -t ${_USERNAME}/${_REPO_NAME} .",
      ]
    secretEnv: ["PM2_PUBLIC_KEY", "PM2_SECRET_KEY"]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker login --username=${_USERNAME} --password=$$PASSWORD"]
    secretEnv: ["PASSWORD"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_USERNAME}/${_REPO_NAME}"]
images:
  - "${_USERNAME}/${_REPO_NAME}"
secrets:
  - kmsKeyName: projects/vpser-d4aae/locations/global/keyRings/keyrings-registry/default/key-registry
    secretEnv:
      PASSWORD: CiQAFtIQkdGbspNF0cUL1xJ6JU7CP+PwFShdhYnDWcyxWoHhiiwSNAAdbQI+xRRRcIYh+TU3V6E1igTvUPslLJ9/8lgL1JmMO11OYEegnlkKRh17L5PI+FuRx+4=
      PM2_PUBLIC_KEY: CiQAFtIQkSPKdPG1x8ttt+IfiVSGNx/Ds206BnNDNrcZ6WQ0ncoSNwAdbQI+MehsO0xb3QeDhKtPBRg6rYvWbbjWS/KiQM8WHMiuOtNJzDedsLD8SaSUnSKQApZ1bAw=
      PM2_SECRET_KEY: CiQAFtIQkbKXLjSMZFHGohTzzBAzpu6xfnXb4MHqgUjZqD4s3rgSRQAdbQI+keQs0C9VIliUwRFtF4RcF8DoQj//yeJOjxI7wmkx1zKudP4vvXG8V52kKF9qAkVoKqyJ9trf97EJY9AGPyDDug==
substitutions:
  _USERNAME: limaofeng
  _REPO_NAME: www.vpsny.app
